"""secciones y grupos de estudiantes

Revision ID: ae95708202ea
Revises: e328f1effd75
Create Date: 2026-08-17 18:48:59.768545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae95708202ea'
down_revision: Union[str, Sequence[str], None] = 'e328f1effd75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'academic_year_id', 'name')
    )
    op.create_table('student_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_group_members',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['student_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'user_id'),
    sa.UniqueConstraint('user_id', 'academic_year_id')
    )
    op.add_column('projects', sa.Column('section_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_projects_section_id', 'projects', 'sections', ['section_id'], ['id'])
    op.add_column('users', sa.Column('section_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_users_section_id', 'users', 'sections', ['section_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_section_id', 'users', type_='foreignkey')
    op.drop_column('users', 'section_id')
    op.drop_constraint('fk_projects_section_id', 'projects', type_='foreignkey')
    op.drop_column('projects', 'section_id')
    op.drop_table('student_group_members')
    op.drop_table('student_groups')
    op.drop_table('sections')
    # ### end Alembic commands ###
